---

# Se eliminaran todos los roles especificados en la variable k8s_rbac_role
#
- name: Delete service account created for Cluster Role
  k8s:
    state: absent 
    name: "{{ item.user }}"
    namespace: "{{ item.namespace }}"
    api_version: v1
    kind: ServiceAccount
  when: item.action == "delete"
  loop: "{{ m7s_rbac_cluster_role }}"

  #- name: Delete a k8s cluster role 
  #  k8s:
  #    name: "{{ item.name }}"
  #    api_version: v1
  #    kind: ClusterRole
  #    state: absent
  #  when: item.action == "delete"
  #  loop: "{{ k8s_rbac_cluster_role }}"

- name: Delete cluster role binding created for Cluster Role
  k8s:
    state: absent 
    name: "{{ item.name }}-binding"
    kind: ClusterRoleBinding
    api_version: v1
  when: item.action == "delete"
  loop: "{{ m7s_rbac_cluster_role }}"

- name: Delete folder with kubeconfig files
  file:
    path: /opt/kubernetes/{{ item.user }}
    state: absent
  when: item.action == "delete"
  loop: "{{ m7s_rbac_cluster_role }}"
