---
# tasks file for generate k8s kubeconfig 
 
- name: Get Role token
  shell: kubectl get secret -n {{ item.namespace }} $(kubectl get sa {{ item.user }} -n {{ item.namespace }} -o jsonpath={.secrets[0].name}) -o jsonpath={.data.token} | base64 -d
  register: "r" 
  with_items: "{{ k8s_rbac_role }}"

- name: Get cluster name
  shell: kubectl config get-contexts $(kubectl config current-context) | awk '{print $3}' | tail -n 1
  register: cluster_name

- name: Get endpoint
  shell: kubectl config view -o jsonpath="{.clusters[?(@.name == \"cluster.local\")].cluster.server}"
  register: endpoint

- debug: msg="{{ cluster_name.stdout }}"

- debug: msg="{{ endpoint.stdout }}"

- debug: msg="{{ r.results[0].stdout }}"
  
#  loop: "{{ k8s_rbac_role }}"
#- name: Generate kubeconfig for Cluster Role
#  template:
#  when: k8s_rbac_cluster_role is defined

  #- name: Create a service account
  #  k8s:
  #    state: present
  #    name: "{{ item.user }}"
  #    namespace: default
  #    api_version: v1
  #    kind: ServiceAccount
  #  loop: "{{ k8s_rbac_cluster_role }}"
  #
  #- name: Create a k8s Cluster Role
  #  k8s:
  #    state: present
  #    definition: "{{ lookup('template', role_path  + '/templates/clusterrole-k8s.yaml.j2') }}"
  #
  #- name: Create a k8s Cluster Role Binding
  #  k8s:
  #    state: present
  #    definition: "{{ lookup('template', role_path + '/templates/clusterrole-binding-k8s.yaml.j2') }}"

#- name: Create a k8s namespace
#  k8s:
#    name: testing
#    namespace: testing
#    api_version: v1
#    kind: namespace
#    state: present
#
#- name: Create a service account
#  k8s:
#    state: present
#    name: "{{ k8s_rbac_namespace }}-user"
#    namespace: "{{ k8s_rbac_namespace }}"
#    api_version: v1
#    kind: ServiceAccount
#
#- name: Create a k8s role with permisions
#  k8s:
#    state: present
#    definition: "{{ lookup('template', role_path  + '/templates/role-k8s.yaml.j2') }}"
#
#- name: Create a k8s RoleBinding
#  k8s:
#    state: present
#    definition: "{{ lookup('template', role_path + '/templates/rolebinding-k8s.yaml.j2') }}"
#
#- name: Create a k8s namespace
#  k8s:
#    name: services-accounts
#    namespace: services-accounts
#    api_version: v1
#    kind: namespace
#    state: present 
#
#- name: Create a service account
#  k8s:
#    state: present
#    name: "{{ item.user }}"
#    namespace: services-accounts
#    api_version: v1
#    kind: ServiceAccount
#  loop: "{{ k8s_rbac_cluster_role }}"
#
#- name: Create a k8s Cluster Role
#  k8s:
#    state: present
#    definition: "{{ lookup('template', role_path  + '/templates/clusterrole-k8s.yaml.j2') }}"
#
#- name: Create a k8s Cluster Role Binding
#  k8s:
#    state: present
#    definition: "{{ lookup('template', role_path + '/templates/clusterrole-binding-k8s.yaml.j2') }}"
