---
# tasks file for k8s-users

- name: Check if Role is defined
  fail:
    msg: "Se debe especificar el ClusterRole existente mediante la variable 'm7s_k8s_user_to_role.role'."
  when: item.role is not defined
  loop: "{{ m7s_k8s_user_to_role }}"

- name: Check for Role type
  fail: 
    msg: "Valores permitidos para la variable user_to_role.role: {{ m7s_k8s_allowed_roles | join(', ') }}"
  when: item.role not in m7s_k8s_allowed_roles
  loop: "{{ m7s_k8s_user_to_role }}"

- name: Check if User is defined
  fail:
    msg: "Se debe especificar el usuario a agregar a el ClusterRole existente mediante la variable 'm7s_k8s_user_to_role.user'."
  when: item.user is not defined
  loop: "{{ m7s_k8s_user_to_role }}"

- name: Create namespace
  k8s:
    state: present
    name: "{{ item.namespace }}"
    namespace: "{{ item.namespace }}"
    kind: Namespace
    api_version: v1
  when: item.action == "create"
  loop: "{{ m7s_k8s_user_to_role }}"

- name: Create a service account
  k8s:
    state: present
    name: "{{ item.user }}"
    namespace: "{{ item.namespace }}"
    api_version: v1
    kind: ServiceAccount
  when: item.action == "create"
  loop: "{{ m7s_k8s_user_to_role }}"

- name: User binding to Role
  k8s:
    state: present
    definition: "{{ lookup('template', role_path + '/templates/user-binding-to-role.yaml.j2') }}"
  vars:
    role: "{{ item.role }}"
    namespace: "{{ item.namespace }}"
    user: "{{ item.user }}"
  when: item.action == "create"
  loop: "{{ m7s_k8s_user_to_role }}"
